# Generated by Django 2.0.3 on 2018-03-08 00:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField(default=None, verbose_name='Имя, город')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Отзыв')),
                ('iframe', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Ссылка на видео с ютуба')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='RepliesImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/stuff', verbose_name='Фото отзыва')),
                ('reply', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.Replies')),
            ],
        ),
    ]
