# Generated by Django 2.0.3 on 2018-03-08 02:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='first_title',
            field=tinymce.models.HTMLField(default=None, verbose_name='Заголовок первого экрана'),
        ),
    ]
