# Generated by Django 2.0.3 on 2018-03-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180308_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalog_url',
            field=models.TextField(blank=True, default=None, max_length=256, null=True, verbose_name='Ссылка на каталог'),
        ),
    ]
