# Generated by Django 2.0.3 on 2018-03-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_catalog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catalog_url',
            field=models.CharField(blank=True, default=None, max_length=556, null=True, verbose_name='Ссылка на каталог'),
        ),
    ]
