# Generated by Django 2.0.3 on 2018-03-08 05:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180308_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default=None, max_length=126, null=True, verbose_name='Дата изготовления')),
                ('title', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(default=None, verbose_name='Описание')),
                ('type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/categories', verbose_name='Фото изделия')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
            options={
                'verbose_name': 'Фото изделия',
                'verbose_name_plural': 'Фото изделия',
            },
        ),
        migrations.AlterModelOptions(
            name='categoryconstext',
            options={'verbose_name': 'Пункт консултации', 'verbose_name_plural': 'Пункты консультации'},
        ),
    ]
