# Generated by Django 2.0.3 on 2018-03-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180308_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimg',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
